# Generated by Django 5.0.2 on 2024-03-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="place",
            field=models.IntegerField(),
        ),
    ]
